### ISSUE TITLE
Show number of views

### ISSUE THREAD

**Issue by kasperpeulen** [nvquanghuy/texpaste#2]
Just a small feature request. What about showing number of views of the note ?

**Comment by nvquanghuy** [comment]
Is this for you to track how many people view your notes or for some other purpose? Is the views available to public too?

**Comment by kasperpeulen** [comment]
Yes,just to see if people are actually reading what I write. :)
I would say also available for public.

**Comment by nvquanghuy** [comment]
OK I see. I'll get it done. For starter it'll be private to the note's owner.

**Comment by nvquanghuy** [comment]
This has been implemented. For the moment the views is only available to the note's owner. It's shown in your Manage Notes page.

Let me know if you have any other questions @kasperpeulen :)
