### ISSUE TITLE
Disqus or other commenting system for each note

### ISSUE THREAD

**Issue by aviaryan** [nvquanghuy/texpaste#3]
It would be nice to have some commenting system so that we can communicate with the viewers and discuss the content of the paste.

Just an example - For my paste http://www.texpaste.com/n/4yam5b1v I will like to ask friends views on why they think the answer can't be 2.

**Comment by nvquanghuy** [comment]
Great idea, thanks for asking @aviaryan . We'll get it added.

**Comment by nvquanghuy** [comment]
This has been added. Take a look: http://www.texpaste.com/n/4yam5b1v
